apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker-deployment
  labels:
    app: flask-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-docker
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
     containers:
      - name: flask-docker
        image: mmeosy/demo-k8s
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-docker-service
  labels: 
    app: flask-docker
     
spec:
  type: LoadBalancer
  selector:
    app: flask-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---


