version: '3'
services:
  azure-vote-back:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: azure-vote-back3
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: mmeosy/demo-k8s
    container_name: azure-vote-front3
    environment:
      REDIS: azure-vote-back3
    ports:
        - "8080:80"
